#!/usr/bin/env bash
# Generate config.local.js at build time from environment variables.
# Runs in Netlify's build step (see netlify.toml). The generated file
# is the same one a developer writes by hand locally.
set -euo pipefail

OUT="config.local.js"

if [[ -z "${SUPABASE_URL:-}" || -z "${SUPABASE_ANON_KEY:-}" ]]; then
  echo "[build-config] ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in Netlify env vars." >&2
  exit 1
fi

cat > "$OUT" <<EOF
// Generated by scripts/build-config.sh — do not edit by hand in Netlify.
window.LUXE_CONFIG = {
  SUPABASE_URL:      "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
};
EOF

echo "[build-config] wrote $OUT"
